CREATE DATABASE IF NOT EXISTS lsr;

USE lsr;

CREATE TABLE IF NOT EXISTS adherant
(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    civilite ENUM('M','F') NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
